# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Sam Barnett | Perth UX Developer"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A Front-end Developer and User Experience Designer based in Perth, WA. I love to bring designs through from pen-and-pad sketches to fully functioning web experiences that people love to use.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: damnsamn
github_username:  damnsamn

include: ['_pages']

# Sass settings
sass:
  add_charset: true
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-autoprefixer

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


# Content:
skills:
    - name: Figma
      src: /assets/images/icons/icon-figma.svg
      href: https://www.figma.com/
    - name: Adobe Creative Cloud
      src: /assets/images/icons/icon-adobe.svg
      href: https://www.adobe.com/au/creativecloud.html/
    - name: HTML5
      src: /assets/images/icons/icon-html.svg
      href: https://developer.mozilla.org/en-US/docs/Web/html/
    - name: CSS3
      src: /assets/images/icons/icon-css.svg
      href: https://developer.mozilla.org/en-US/docs/Web/css/
    - name: Sass
      src: /assets/images/icons/icon-sass.svg
      href: https://sass-lang.com/
    - name: Javascript
      src: /assets/images/icons/icon-js.svg
      href: https://developer.mozilla.org/en-US/docs/Web/javascript/
    - name: Angular
      src: /assets/images/icons/icon-angular.svg
      href: https://www.angular.io/
    - name: Git
      src: /assets/images/icons/icon-git.svg
      href: https://git-scm.com/
