title: "Sam Barnett | Perth UX Developer"
suffix: "Sam Barnett, Perth UX Developer"
email: your-email@example.com
desc:  >- # this means to ignore newlines until "baseurl:"
  A Front-end Developer and User Experience Designer. I design and develop websites and other digital experiences, currently based in Perth, Western Australia.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samuelbar.net" # the base hostname & protocol for your site, e.g. http://example.com

host: 0.0.0.0

include: ["_pages"]
collections_dir: _collections
collections:
  snippets:
    output: true
    permalink: /:collection/:title
  projects:
    output: true
    permalink: /:collection/:title
    sort_by: order
# Sass settings
sass:
  add_charset: true
  sass_dir: _sass
  style: compressed

# plugins:
#   - jekyll-autoprefixer
